### ISSUE TITLE
sha256.hmac return garbled hash value

### ISSUE THREAD

**Issue by didxga** [dchest/fast-sha256-js#5]
I was trying to use the sha256.hmac function to generate hmac sha256 hash, but I got some garbled code.

```
//convert String to Uint8Array
var msg = new TextEncoder("utf-8").encode("/v2/radios?page=1&size=10&catalog=all:7690d85d-7777-2930-040c-9241b52682ab");
var key  = new TextEncoder("utf-8").encode("q23IN6hB7p"); 
var hash = sha256.hmac(key, msg);
//convert Uint8Array to String
console.log(new TextDecoder("utf-8").decode(hash));  // result is garbled code： gUm7_�������)���V�Ύ����kb�l�T
```
version: v1.0.0
browser: Chrome 62

**Comment by dchest** [comment]
What did you expect it to return?

**Comment by didxga** [comment]
I expected it to return a hash string like: `"eac1jklqa0c9f4e700ccab992dfb36a6d2e30e34sd01c8476f3cio27633f187"`

**Comment by dchest** [comment]
The returned value is a binary (0-255) hash, so if you want a hex representation convert it to hex. You never want to convert binary values from utf-8 unless you know they represent text encoded as utf-8 in the first place.

**Comment by didxga** [comment]
Thanks @dchest. for clarification.

For someone running into the same problem, I post my solution here:

```
//convert String to Uint8Array
var msg = new TextEncoder("utf-8").encode("/v2/radios?page=1&size=10&catalog=all:7690d85d-7777-2930-040c-9241b52682ab");
var key  = new TextEncoder("utf-8").encode("q23IN6hB7p"); 
var hash = sha256.hmac(key, msg);
//convert Uint8Array to hex string
var hashStr = Array.from(hash, function(byte) {
    return ('0' + (byte & 0xFF).toString(16)).slice(-2);
  }).join('');
```

**Comment by dchest** [comment]
You're welcome! If you already use TextEncoder, it's easier to use it for hex too as in my edited comment.

**Comment by didxga** [comment]
@dchest I tried few other heavyweight libraries, for the same API I am using here, they accept and return both string value instead of Uint8Array.

- What is your consideration to use Uint8Array when design this API? 
- Is it possible to update the user guide to include code example on conversion between Uint8Array to String?

**Comment by dchest** [comment]
* It was popular in JavaScript libraries to create many methods, like hexDigest(), base64Digest(), etc — there are many different representations of hashes — and also accept strings instead of Uint8Arrays. This made libraries include hex, base64, utf8, etc. encoders/decoders. So imaging you're using AES, SHA256, ZIP, PNG, etc. and all of them include their own, perhaps buggy, encoders/decoders, inflating code size. This was mostly an artifact of JavaScript not having typed arrays, so bytes were represented either as strings or as Arrays. Now that we have typed arrays and TextEncoder/TextDecoder (or Buffer in Node.js), it's time to put an end to this practice.
* There's a small note about it in the docs ("Functions accept and return Uint8Arrays. To convert strings, use external library (for example, nacl.util)"), but I'd welcome a pull request to add something like this to examples:

```
const result = hasher.digest();
// or if you need a hex representation:
const hexResult = new TextEncoder("hex").encode(result);
```

**Comment by didxga** [comment]
@dchest I will try to improve this part of doc a little bit, going to do a pull request.

But I think `const hexResult = new TextEncoder("hex").encode(result);` returns Uint8Array not a String, what method do you recommend for String conversion?

**Comment by dchest** [comment]
Or, right, sorry, it indeed returns Uint8Array and "hex" is not supported in some browsers. Not sure then, maybe Node.js's `Buffer.from(result).toString('hex')`?
